# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "CI"

on:
  pull_request:
  push:
    branches:
      - "main"

env:
  COMPOSER_ROOT_VERSION: "1.99.99"

jobs:
  xml-validation:
    name: "XML Validation"
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.4"
          - "8.0"
        operating-system:
          - "ubuntu-latest"
          - "windows-latest"
        include:
          - php-version: "8.0"
            composer-options: "--ignore-platform-reqs"
    steps:
      - name: "Configure Git"
        if: ${{ matrix.operating-system == 'windows-latest' }}
        run: |
          git config --system core.autocrlf false
          git config --system core.eol lf
      - uses: "actions/checkout@v2"
      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
      - uses: "ramsey/composer-install@v1"
        with:
          dependency-versions: "${{ matrix.dependencies }}"
          composer-options: "${{ matrix.composer-options }}"
      - name: "Validate ruleset"
        run: "composer test"
